__author__ = 'pgm'

STRING = "Core/String"
INSTANCE_OF = "Core/Thing/InstanceOf"
NAME_IS_UNIQUE = "Core/Type/NameIsUnique"
IS_UNIQUE = "Core/Property/IsUnique"
REVERSE_PROPERTY = "Core/Type/ReverseProperty"
PROPERTY = "Core/Type/Property"
INCLUDED_TYPE = "Core/Type/IncludedType"
ID = "Core/Thing/ID"
NAME = "Core/Thing/Name"
DESCRIPTION = "Core/Thing/Description"
EXPECTED_TYPE = "Core/Type/ExpectedType"
INTEGER = "Core/Integer"
REAL = "Core/Real"
THING = "Core/Thing"
TYPE = "Core/Type"
BOOLEAN = "Core/Boolean"
PROPERTY_TYPE = "Core/Property"

